### ISSUE TITLE
Extends out of the box

### ISSUE THREAD

**Issue by MicMicMon** [joeattardi/emoji-button#12]
What an amazing work, thanks!

Ran into this glitch (notice the last line bleeding below the separation line):

![image](https://user-images.githubusercontent.com/37897072/70448683-01c58480-1aa1-11ea-937d-da52dd60f0cb.png)

Simply using this in my code solved the issue for me:
```css
.emoji-picker__tab-body {
  margin-top: 0px !important;
}
```

Any idea what could be causing this, and if it is the right way to fix the issue?
