### ISSUE TITLE
[feature] Customizable z-index

### ISSUE THREAD

**Issue by MicMicMon** [joeattardi/emoji-button#13]
When using inside a `mat-dialog` in Angular, the picker does not show because it is hidden behind the dialog component.

I fixed this a global css style:
```css
.emoji-picker {
  z-index: 1001; // Show over mat-dialog
}
```

It would be nice to be able to customize the z-index through the config object.
