### ISSUE TITLE
Is it possible to exclude some emoji from the picker?

### ISSUE THREAD

**Issue by mattWalters0** [joeattardi/emoji-button#160]
For example I want to exclude emoji that have already been selected.

**Comment by joeattardi** [comment]
I'm not crazy about building such a specific use case into the picker, however I can look into possibly extending the plugin infrastructure so that it would be possible to create a plugin that does this. Will keep this in mind for v5.

**Comment by wallingm** [comment]
You could use css to hide specific emojis:
```css
.emoji-picker__emoji[data-emoji="😎"] { display:none }
```
or use jquery and css to hide after one is selected:
```javascript
picker.on('emoji', selection => {
    $('.emoji-picker__emoji[data-emoji="'+selection.emoji+'"]').addClass('hide');
});
```
```css
.emoji-picker__emoji.hide { display:none }
```
